database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: qwerty
  #password: root
  #password: qwerty
  # or root

  #open -a Google\ Chrome --args --disable-web-security --user-data-dir
  #open -a Google\ Chrome --args --enable-web-security --user-data-dir

  url: jdbc:postgresql://localhost:5432/swatkats
  # or 5432
  # or 5433
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32

server:
  rootPath: '/swatkats/*'