database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: qwerty
  #password: root
  # or root
  url: jdbc:postgresql://localhost:5433/swatkats
  # or 5432
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32

server:
  rootPath: '/swatkats/*'